### ISSUE TITLE
Safari blocks loading slides when used in embedded shared schedule 

### ISSUE THREAD

**Issue by alanclayton** [Rise-Vision/rise-slides#57]
Shared schedule embedded on https://alpineschools.org includes a presentation using slides component. If you open with Safari 14.0.3 the slides content never shows. 

![image](https://user-images.githubusercontent.com/6854911/118320398-d29b1a00-b4c1-11eb-9143-1e5cc34bd38a.png)

**Comment by olegrise** [comment]
I tested the same shared schedule embedded in my test website as well as other schedules with embedded slides and every time slides are showing. It seems that the problem is specific to the alpineschools.org website only.

I was able to reproduce the error in Safari, but not in Chrome. The error occurs when we check access to the iFrame window [here](https://github.com/Rise-Vision/rise-slides/blob/2f62bef5a434d60a6ecda4cc649f65ed49071a95/src/rise-slides.js#L92). To be more specific, checking for `tag.contentDocument` is what generates the error. Basically the error in the console is not related to the slides not showing.

This error is harmless. It does not affect the code execution. I was trying to suppress it by adding `try...catch`, but it does not work. Considering that the error is harmless and we can't really do anything about it and slides are not showing on alpineschools.org website only, I'm going to close this issue.
